#!/bin/bash

Color_Off='\033[0m'
BGreen='\033[1;32m'
BRed='\033[1;31m'

venv_activate() {
    enjoy() {
        echo -e "Enjoy working on your $(basename "$PWD") project, ${USER^}!"
        echo
    }

    spin_up() {
        if [ -n "$1" ]; then
            if [ -f "$1/bin/activate" ]; then
                echo "Launching a new Bash shell with the virtual environment activated."
                bash -c "source \"$1/bin/activate\"; exec bash -i" || echo "Failed to activate: $1"
            else
                echo "Error: '$1/bin/activate' not found." >&2
                return 2
            fi
        else
            echo "Error: No virtual environment path provided to spin_up." >&2
            return 1
        fi
    }

    if [ -d "$PWD/.venv" ]; then
        echo -e "${BGreen}.venv${Color_Off} found in: $PWD"
        echo -e "${BGreen}.venv${Color_Off} activated."
        venv_path="$PWD/.venv"
        enjoy
        spin_up "$venv_path"
        return $?
    elif [ -d "$PWD/venv" ]; then
        echo -e "${BGreen}venv${Color_Off} found in: $PWD"
        echo -e "${BGreen}venv${Color_Off} activated."
        venv_path="$PWD/venv"
        enjoy
        spin_up "$venv_path"
        return $?
    else
        echo -e "Error: No ${BRed}venv${Color_Off} or ${BRed}.venv$Color_Off directory found." >&2
        return 1
    fi

}

venv_activate
